### ISSUE TITLE
Could not open file

### ISSUE THREAD

**Issue by rborgesm** [sestaton/Pairfq#10]
I ran pairfq on several fastq.gz files and for some (but not all of them) I am getting the following error: 
"ERROR: Could not open file: /folder/file_f.fastq.gz"

However, I am able to do "zcat /folder/file_f.fastq.gz | head" and the file is there. I cannot detect any obvious differences between the files that do run and the ones that give this message. Any idea as to what would cause this?

Thank you

**Comment by sestaton** [comment]
Can you show the command that produced the error? Also, show after that the 'zcat' command demonstrating that the files is there. I'm guessing it is a path issue or it could be permissions on the files.

Thanks.

**Comment by rborgesm** [comment]
Thank you for your help. 

This was the command used:

`R1=$1  # filename of R1`

`R2=$2  # filename of R2 `

`#names for pairfq files `
`commonR1=${R1/R1/_common.R1} `
`commonR2=${R2/R2/_common.R2} `
`uniqueR1=${R1/R1/_unique.R1} `
`uniqueR2=${R2/R2/_unique.R2}`

`cd /data/rawfiles/../filtered_polyA`
`$pairfq_path/pairfq makepairs -f /data/rawfiles/../filtered_polyA/$R1 -r /data/rawfiles/../filtered_polyA/$R2 -fp /data/rawfiles/../filtered_polyA/$commonR1 -rp /data/rawfiles/../filtered_polyA/$commonR2 -fs /data/rawfiles/../filtered_polyA/$uniqueR1 -rs /data/rawfiles/../filtered_polyA/$uniqueR2 -c 'gzip' && \ 
`

The error is:
 `ERROR: Could not open file: /data/rawfiles/../filtered_polyA/file.R1.fastq.gz
`

And the zcat command results: 

`zcat /data/rawfiles/../filtered_polyA/file.R1.fastq.gz | head

@ST-E00203:241:HVN2HCCXX:5:1101:12895:15602 1:N:0:CAGATC
AGATGCAGAGAAAACAGCTCCTTGGTGAATTGATAAGTAAAGGCAGAAAAGATTATATGTCATACCTCCATTGGGGAATAAGCATAACCCTGAGATTCTTACTACTGATGAGAACATTATCTGCATATGCCAAAAAATTTTAAGCAAATG
+ST-E00203:241:HVN2HCCXX:5:1101:12895:15602 1:N:0:CAGATC
AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
@ST-E00203:241:HVN2HCCXX:5:1101:13037:15602 1:N:0:CAGATC
TGAGTTGCAGCAGCAGCAGGCTGAGTACGAGGACCTTATGGGACAGAAAGATGACCTCAACTCCCAGCTCCAGGAGTCATTACGGGCCAATAGTCGACTGCTGGAACA
+ST-E00203:241:HVN2HCCXX:5:1101:13037:15602 1:N:0:CAGATC
AAFFFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKK
@ST-E00203:241:HVN2HCCXX:5:1101:13119:15602 1:N:0:CAGATC
GTTAAGATCTTTTCATGAACTGGGAATTACAATTTGTTAAATATAATTAAAACAATATATTTATGTACTTTTTACAATTAAAAAAACAGGCTATTGATAGACTAGGAGGAATATATTTGCCAGCCCTCTAACTGGCAGAGTGGATTCAGG
`

Permissions for file are:

`-rwxrw----. 1 user group  8861014573 Jul 22 18:08 file.R1.fastq.gz`
`-rwxrw----. 1 user group  9096862999 Jul 22 19:31 file.R2.fastq.gz`

**Comment by sestaton** [comment]
Thanks for the information. The issue was that filepaths were assumed to be absolute so things like "/data/rawfiles/../filtered_polyA/$R1" would not work because the file is actually at "/data/rawfiles/filtered_polyA/$R1."

This could be handled in the shell script but I'm glad this was pointed out. Please update Pairfq from the master branch and try again. It should handle these cases now.

**Comment by rborgesm** [comment]
Great, this seemed to be the issue. Thank you!

**Comment by sestaton** [comment]
Glad to hear it! And, thanks for the update. I'll mark a new release/version with this change.
