### ISSUE TITLE
seperation

### ISSUE THREAD

**Issue by krishnakatyal** [sestaton/Pairfq#12]
hello i have a fastq file which is not inter leafed it has around 1 million sequences with first half million forward rest half million reverse can you please suggest me how to seperate them using pairfq

**Comment by sestaton** [comment]
The 'splitpairs' program should work just the same. It does not require the pairs to be interleaved prior to splitting them. I would try the operation as you would for any file with paired reads:

    pairfq splitpairs -i s_1_interl.fq -f s_1_1_p.fq -r s_1_2_p.fq

I believe if you run the `pairfq splitpairs` command with no arguments it will print more info, but the command above will do the job.

**Comment by krishnakatyal** [comment]
@sestaton thanks alot 👍
