### ISSUE TITLE
pairfq usage

### ISSUE THREAD

**Issue by vgaout** [sestaton/Pairfq#13]
Hi to all,

I am trying to use **meRanGs** align program and I achieve the following error when I run the program:

`ERROR SRR3583357_1_trimmed.fq and SRR3583357_2_trimmed.fq are not properly paired, you may use pairfq (S. Evan Staton) tool to pair and sort the mates at script/meRanGs.pl line 4149, <GEN10> line 4.`

So now, I am trying to use **pairfq** program. In this case I have forward reads and reverse reads obtained after trimming with trim galore so I am runing the following line:

`perl pairfq makepairs -f ~/SRR3583357_1.fastq_trimming_report.txt -r ~/SRR3583357_2.fastq_trimming_report.txt
`
and all the time I obtained the following error: 

`ERROR: Command line not parsed correctly. Check input.
`
I saw thar there are various options that are required in the program but I only have two inputs, one with the forward paired reads and other with the reverse ones, so I do not know what other files I have to use as input.

Thank you to all, I hope somebody could help me.
Vera

**Comment by sestaton** [comment]
Please see the usage example on the wiki: https://github.com/sestaton/Pairfq/wiki/makepairs

You need to supply additional arguments for the command (specifically, the paired and singleton output files).

**Comment by sestaton** [comment]
Please comment if the documentation is not clear and I will update this issue.
